Add basic layout for home page with minimal styling
RossJ24/STEP-starter pull request #1
Opened 2020-05-28 16:45 UTC by RossJ24

Added an image of myself, as well as changed the layout to be more centered. Minimal styling was done, and buttons were added.

2020-05-28 23:02 UTC, KillianLeC commented on portfolio/src/main/webapp/interests.html
> +<html>
nit: newline

2020-05-28 23:03 UTC, KillianLeC commented on portfolio/src/main/webapp/script.js
> +      ['I am conversational in Chinese!', 'My first programming language was Java', 'The programming language I like the most right now is Dart', 'The programming language I want to learn next is Gol
format this line so that I can see entire line in without scrolling.

2020-05-28 23:03 UTC, KillianLeC commented on portfolio/src/main/webapp/script.js
> +function randomFactAboutRoss() {
potentially rename this to "getRandomFactAboutRoss()"

2020-05-28 23:05 UTC, KillianLeC commented on portfolio/src/main/webapp/script.js
> +function goToLinkedIn(){
openLinkedInUrl, same with github below

2020-05-28 23:05 UTC, KillianLeC commented on portfolio/src/main/webapp/script.js
> +    window.open("https://github.com/RossJ24","_blank")
missing semi-colon at EOL

2020-05-28 23:05 UTC, KillianLeC commented on portfolio/src/main/webapp/skills.html
> +            <img id="interestimg" src="./images/flutter.png"></img>
generally, each id should be unique.

2020-05-28 23:07 UTC, KillianLeC requested changes

2020-05-28 23:07 UTC, KillianLeC commented on portfolio/src/main/webapp/skills.html
> +
delete extra line

2020-05-28 23:07 UTC, KillianLeC commented on portfolio/src/main/webapp/skills.html
> +            <img id="interestimg" src="./images/flutter.png"></img>
To tag on, seeing this is used for CSS. This could be done using a class rather than an id.

2020-05-29 17:07 UTC, KillianLeC requested changes

2020-05-29 17:07 UTC, KillianLeC commented on portfolio/src/main/webapp/interests.html
> +            <img class="interestimg" src="./images/flutter.png"></img>
nit: naming convention is to put - between words for legability. Same for ids

2020-05-29 17:07 UTC, KillianLeC commented on portfolio/src/main/webapp/interests.html
> +                    <span id="bottomnavbuttonlabel">
nit: naming convention

2020-05-29 17:07 UTC, KillianLeC commented on portfolio/src/main/webapp/interests.html
> +            <p></p>
extra element? If this is to add space between, you can either add margin on the element below or above.

2020-05-29 17:07 UTC, KillianLeC commented on portfolio/src/main/webapp/script.js
> +      'My first programming language was Java!',
nit: format to be on same column

2020-05-29 17:07 UTC, KillianLeC commented on portfolio/src/main/webapp/script.js
> +  const greeting = facts[Math.floor(Math.random() * facts.length)];
variable should be renamed as it's in relation to facts rather than greetings.

2020-05-29 17:07 UTC, KillianLeC commented on portfolio/src/main/webapp/script.js
> +}
nit: newline

2020-05-29 17:07 UTC, KillianLeC commented on portfolio/src/main/webapp/script.js
>   * Adds a random greeting to the page.
update comment

2020-05-29 17:07 UTC, KillianLeC commented on portfolio/src/main/webapp/style.css
> +}
nit: newline

2020-05-29 17:15 UTC, RossJ24 commented on portfolio/src/main/webapp/script.js
> +}
Which newline specifically?

2020-05-29 20:39 UTC, KillianLeC approved these changes
Looks good

2020-05-29 20:39 UTC, KillianLeC approved these changes

2020-06-01 15:58 UTC, merged