Rossdev5
RossJ24/STEP-starter pull request #5
Opened 2020-06-10 20:04 UTC by RossJ24

2020-06-12 04:17 UTC, KillianLeC requested changes
Looks good so far, just make sure to move over changes from other pull request to here.

2020-06-12 04:17 UTC, KillianLeC commented on portfolio/src/main/java/com/google/sps/servlets/DataServlet.java
> +    public static final String COMMENT_ENTITY = "comment";
Add to ServletUtil

2020-06-12 04:17 UTC, KillianLeC commented on portfolio/src/main/java/com/google/sps/servlets/DataServlet.java
> +        }
This should be updated based on discussion in other pull request

2020-06-12 04:17 UTC, KillianLeC commented on portfolio/src/main/java/com/google/sps/servlets/DataServlet.java
> +        try{
try {

2020-06-12 04:17 UTC, KillianLeC commented on portfolio/src/main/java/com/google/sps/servlets/DataServlet.java
> +        String jsonstring = req.getParameter("comment");
change string to be a global field

2020-06-12 04:17 UTC, KillianLeC commented on portfolio/src/main/java/com/google/sps/servlets/DataServlet.java
> +import com.google.gson.*;
only import specific classes

2020-06-12 04:17 UTC, KillianLeC commented on portfolio/src/main/java/com/google/sps/servlets/DataServlet.java
> +            res.sendRedirect("/index.html");
same, set these (including /error.html) as global fields

2020-06-12 04:17 UTC, KillianLeC commented on portfolio/src/main/java/com/google/sps/servlets/DeleteDataServlet.java
> +        for (Entity entity : results.asIterable()){
results.asIterable()) {

2020-06-12 04:17 UTC, KillianLeC commented on portfolio/src/main/webapp/script.js
> +  if(fact === 'I have been to 4 continents!' || fact === 'I have been to more than 10 countries!') {
add new variable before query on array 'facts' that indicates the index. Then check that index here instead of string.

2020-06-12 04:17 UTC, KillianLeC commented on portfolio/src/main/webapp/script.js
> +    let res = await fetch('/data?limit='+limit);
`/data?limit=${limit}`

2020-06-12 04:17 UTC, KillianLeC commented on portfolio/src/main/webapp/script.js
> +    }
update based on other pull request

2020-06-12 04:17 UTC, KillianLeC commented on portfolio/src/main/webapp/script.js
> +}
nit: new line

2020-06-16 16:02 UTC, KillianLeC requested changes

2020-06-16 16:02 UTC, KillianLeC commented on portfolio/src/main/java/com/google/sps/servlets/DataServlet.java
> +        int limit = Integer.parseInt(req.getParameter("limit"));
make this a global field in ServletUtil

2020-06-16 16:02 UTC, KillianLeC commented on portfolio/src/main/java/com/google/sps/servlets/ServletUtil.java
> +}
nit: newline

2020-06-16 16:02 UTC, KillianLeC commented on portfolio/src/main/java/com/google/sps/servlets/DataServlet.java
> +        }
This can be a one-line, follow suggestion made in other pull request (should be a stack overflow link)

2020-06-16 16:02 UTC, KillianLeC commented on portfolio/src/main/webapp/script.js
> +  let currentFactIndex = facts.indexOf(fact);
const currentFactIndex = Math.floor(Math.random() * facts.length());
const fact = facts[currentFactIndex]

2020-06-16 16:02 UTC, KillianLeC commented on portfolio/src/main/webapp/script.js
> +    document.getElementById("map").style.height = "0px";
create a variable outside the if / else statement, then change it's style inside the if / else statement

2020-06-16 16:02 UTC, KillianLeC commented on portfolio/src/main/webapp/script.js
> +  else{
else {

2020-06-17 00:58 UTC, tianxiao25 commented on portfolio/src/main/webapp/script.js
> +  if(currentFactIndex === 2 || currentFactIndex === 3) {
Have comment above about why diff style needed and how does those hard code index chosen. 

Make them as global var at top as well.

2020-06-17 00:58 UTC, tianxiao25 commented on portfolio/src/main/webapp/script.js
> +
indentation. remove extra new line.

2020-06-17 00:58 UTC, tianxiao25 commented on portfolio/src/main/webapp/script.js
> +  let previouslyVisitedLocations = {
same for this one. Declare it as global map at top.

2020-06-25 20:47 UTC, KillianLeC approved these changes
Looks great, sorry for the delay!

2020-06-25 21:18 UTC, merged